#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Jun 13, 2024 10:12:44 PM +0545  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import project1_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return
    project1_support.root.tk.eval('set ::xframe #d9d9d9')
    project1_support.root.tk.eval('set ::xfore #000000')
    project1_support.root.tk.eval('set ::ana2color beige')
    project1_support.root.tk.eval('set ::_tabfg1 black')
    project1_support.root.tk.eval('set ::_tabfg2 white')
    project1_support.root.tk.eval('set ::_tabbg1 #d9d9d9')
    project1_support.root.tk.eval('set ::_tabbg2 gray40')
    project1_support.root.tk.eval('set ::_bgmode light')        
    try: project1_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'page-legacy.tcl'))
    except: pass
    style = ttk.Style()
#     style.theme_use('page-legacy')
    style.configure('.', font = "TkDefaultFont")
    project1_support.root.tk_setPalette(
            foreground = '#000000',
            background = '#d9d9d9',
            activeForeground = 'black',
            activeBackground = '#d9d9d9',
            selectForeground = 'black',
            selectBackground =  '#d9d9d9')
    _style_code_ran = 1

class geoto_stitcher:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("684x888+580+884")
        top.minsize(1, 1)
        top.maxsize(1905, 1050)
        top.resizable(1,  1)
        top.title("GeoTo Stitcher")

        self.top = top
        self.selectedButton = tk.IntVar()

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        _style_code()
        self.close_program = ttk.Button(self.top)
        self.close_program.place(relx=0.409, rely=0.955, height=31, width=80)
        self.close_program.configure(command=project1_support.close_program)
        self.close_program.configure(text='''Close''')
        self.close_program.configure(compound='left')

        self.auto_fill = ttk.Button(self.top)
        self.auto_fill.place(relx=0.851, rely=0.954, height=31, width=80)
        self.auto_fill.configure(command=project1_support.auto_fill)
        self.auto_fill.configure(text='''Auto Fill''')
        self.auto_fill.configure(compound='left')

        self.process_pgf_block = tk.LabelFrame(self.top)
        self.process_pgf_block.place(relx=0.029, rely=0.215, relheight=0.118
                , relwidth=0.946)
        self.process_pgf_block.configure(relief='groove')
        self.process_pgf_block.configure(font="-family {DejaVu Sans} -size 10")
        self.process_pgf_block.configure(text='''Process PGF''')

        self.process_pgf = ttk.Progressbar(self.process_pgf_block)
        self.process_pgf.place(relx=0.553, rely=0.248, relwidth=0.411
                , relheight=0.0, height=19, bordermode='ignore')
        self.process_pgf.configure(length="281")

        self.start_process_pgf = ttk.Button(self.process_pgf_block)
        self.start_process_pgf.place(relx=0.073, rely=0.581, height=31, width=80
                , bordermode='ignore')
        self.start_process_pgf.configure(command=project1_support.start_process_pgf)
        self.start_process_pgf.configure(text='''Start''')
        self.start_process_pgf.configure(compound='left')

        self.Label5 = tk.Label(self.process_pgf_block)
        self.Label5.place(relx=0.634, rely=0.457, height=21, width=102
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(anchor='w')
        self.Label5.configure(compound='left')
        self.Label5.configure(font="-family {DejaVu Sans} -size 10")
        self.Label5.configure(text='''Recording:''')

        self.process_pgf_rec = tk.Label(self.process_pgf_block)
        self.process_pgf_rec.place(relx=0.784, rely=0.457, height=21, width=65
                , bordermode='ignore')
        self.process_pgf_rec.configure(activebackground="#f9f9f9")
        self.process_pgf_rec.configure(anchor='w')
        self.process_pgf_rec.configure(compound='left')
        self.process_pgf_rec.configure(font="-family {DejaVu Sans} -size 10")
        self.process_pgf_rec.configure(text='''0''')

        self.Label7 = tk.Label(self.process_pgf_block)
        self.Label7.place(relx=0.624, rely=0.686, height=21, width=66
                , bordermode='ignore')
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(anchor='w')
        self.Label7.configure(compound='left')
        self.Label7.configure(font="-family {DejaVu Sans} -size 10")
        self.Label7.configure(text='''Status:''')

        self.process_pgf_status = tk.Label(self.process_pgf_block)
        self.process_pgf_status.place(relx=0.72, rely=0.686, height=21, width=140
                , bordermode='ignore')
        self.process_pgf_status.configure(activebackground="#f9f9f9")
        self.process_pgf_status.configure(anchor='w')
        self.process_pgf_status.configure(compound='left')
        self.process_pgf_status.configure(font="-family {DejaVu Sans} -size 10")
        self.process_pgf_status.configure(text='''None''')

        self.pgf_threads = tk.Spinbox(self.process_pgf_block, from_=1.0, to=100.0)
        self.pgf_threads.place(relx=0.219, rely=0.248, relheight=0.219
                , relwidth=0.117, bordermode='ignore')
        self.pgf_threads.configure(activebackground="#f9f9f9")
        self.pgf_threads.configure(background="white")
        self.pgf_threads.configure(font="-family {DejaVu Sans} -size 10")
        self.pgf_threads.configure(highlightbackground="black")
        self.pgf_threads.configure(selectbackground="#c4c4c4")
        self.value_list = ['100',]
        self.pgf_threads.configure(values=self.value_list)

        self.pgf_label = tk.Label(self.process_pgf_block)
        self.pgf_label.place(relx=0.029, rely=0.248, height=27, width=123
                , bordermode='ignore')
        self.pgf_label.configure(activebackground="#f9f9f9")
        self.pgf_label.configure(anchor='w')
        self.pgf_label.configure(compound='left')
        self.pgf_label.configure(font="-family {DejaVu Sans} -size 10")
        self.pgf_label.configure(text='''No of Threads''')

        self.upload_pgf = tk.Button(self.process_pgf_block)
        self.upload_pgf.place(relx=0.292, rely=0.581, height=33, width=73
                , bordermode='ignore')
        self.upload_pgf.configure(activebackground="beige")
        self.upload_pgf.configure(borderwidth="2")
        self.upload_pgf.configure(command=project1_support.upload_pgf)
        self.upload_pgf.configure(compound='left')
        self.upload_pgf.configure(font="-family {DejaVu Sans} -size 10")
        self.upload_pgf.configure(text='''Upload''')

        self.stitch_360high_block = tk.LabelFrame(self.top)
        self.stitch_360high_block.place(relx=0.029, rely=0.597, relheight=0.153
                , relwidth=0.946)
        self.stitch_360high_block.configure(relief='groove')
        self.stitch_360high_block.configure(font="-family {DejaVu Sans} -size 10")
        self.stitch_360high_block.configure(text='''Stitch 360high''')

        self.generate_pts = ttk.Button(self.stitch_360high_block)
        self.generate_pts.place(relx=0.077, rely=0.706, height=31, width=130
                , bordermode='ignore')
        self.generate_pts.configure(command=project1_support.generate_pts)
        self.generate_pts.configure(text='''Generate PTS''')
        self.generate_pts.configure(compound='left')

        self.Label6 = tk.Label(self.stitch_360high_block)
        self.Label6.place(relx=0.025, rely=0.169, height=24, width=123
                , bordermode='ignore')
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(anchor='w')
        self.Label6.configure(compound='left')
        self.Label6.configure(font="-family {DejaVu Sans} -size 10")
        self.Label6.configure(text='''PTS Template''')

        self.Label6_1 = tk.Label(self.stitch_360high_block)
        self.Label6_1.place(relx=0.031, rely=0.419, height=24, width=93
                , bordermode='ignore')
        self.Label6_1.configure(activebackground="#f9f9f9")
        self.Label6_1.configure(anchor='w')
        self.Label6_1.configure(compound='left')
        self.Label6_1.configure(font="-family {DejaVu Sans} -size 10")
        self.Label6_1.configure(text='''PTS Big''')

        self.start_stitch_360high = ttk.Button(self.stitch_360high_block)
        self.start_stitch_360high.place(relx=0.355, rely=0.706, height=31
                , width=90, bordermode='ignore')
        self.start_stitch_360high.configure(command=project1_support.start_stitch_360high)
        self.start_stitch_360high.configure(text='''Start''')
        self.start_stitch_360high.configure(compound='left')

        self.upload_360high = tk.Button(self.stitch_360high_block)
        self.upload_360high.place(relx=0.587, rely=0.706, height=33, width=73
                , bordermode='ignore')
        self.upload_360high.configure(activebackground="beige")
        self.upload_360high.configure(borderwidth="2")
        self.upload_360high.configure(command=project1_support.upload_360high)
        self.upload_360high.configure(compound='left')
        self.upload_360high.configure(font="-family {DejaVu Sans} -size 10")
        self.upload_360high.configure(text='''Upload''')

        self.upload_360high_1 = tk.Button(self.stitch_360high_block)
        self.upload_360high_1.place(relx=0.773, rely=0.706, height=33, width=103
                , bordermode='ignore')
        self.upload_360high_1.configure(activebackground="beige")
        self.upload_360high_1.configure(borderwidth="2")
        self.upload_360high_1.configure(command=project1_support.upload_pts)
        self.upload_360high_1.configure(compound='left')
        self.upload_360high_1.configure(font="-family {DejaVu Sans} -size 10")
        self.upload_360high_1.configure(text='''Upload PTS''')

        self.select_pts_big = ttk.Button(self.stitch_360high_block)
        self.select_pts_big.place(relx=0.85, rely=0.382, height=31, width=80
                , bordermode='ignore')
        self.select_pts_big.configure(command=project1_support.select_template_big)
        self.select_pts_big.configure(text='''Select''')
        self.select_pts_big.configure(compound='left')

        self.TButton1_1 = ttk.Button(self.stitch_360high_block)
        self.TButton1_1.place(relx=0.85, rely=0.162, height=31, width=80
                , bordermode='ignore')
        self.TButton1_1.configure(command=project1_support.select_template)
        self.TButton1_1.configure(text='''Select''')
        self.TButton1_1.configure(compound='left')

        self.pts_template = tk.Entry(self.stitch_360high_block)
        self.pts_template.place(relx=0.201, rely=0.169, height=26, relwidth=0.628
                , bordermode='ignore')
        self.pts_template.configure(background="white")
        self.pts_template.configure(font="-family {DejaVu Sans Mono} -size 10")
        self.pts_template.configure(selectbackground="#c4c4c4")

        self.pts_template_big = tk.Entry(self.stitch_360high_block)
        self.pts_template_big.place(relx=0.201, rely=0.368, height=26
                , relwidth=0.628, bordermode='ignore')
        self.pts_template_big.configure(background="white")
        self.pts_template_big.configure(font="-family {DejaVu Sans Mono} -size 10")
        self.pts_template_big.configure(selectbackground="#c4c4c4")

        self.stitch_360low_block = tk.LabelFrame(self.top)
        self.stitch_360low_block.place(relx=0.029, rely=0.755, relheight=0.111
                , relwidth=0.946)
        self.stitch_360low_block.configure(relief='groove')
        self.stitch_360low_block.configure(font="-family {DejaVu Sans} -size 10")
        self.stitch_360low_block.configure(text='''Generate Tiles''')

        self.process_stitch_360low = ttk.Progressbar(self.stitch_360low_block)
        self.process_stitch_360low.place(relx=0.553, rely=0.253, relwidth=0.411
                , relheight=0.0, height=19, bordermode='ignore')
        self.process_stitch_360low.configure(length="281")

        self.start_sitch_360low = ttk.Button(self.stitch_360low_block)
        self.start_sitch_360low.place(relx=0.073, rely=0.596, height=31, width=80
                , bordermode='ignore')
        self.start_sitch_360low.configure(command=project1_support.start_stitch_360low)
        self.start_sitch_360low.configure(text='''Start''')
        self.start_sitch_360low.configure(compound='left')

        self.Label5_2_1 = tk.Label(self.stitch_360low_block)
        self.Label5_2_1.place(relx=0.634, rely=0.455, height=20, width=102
                , bordermode='ignore')
        self.Label5_2_1.configure(activebackground="#f9f9f9")
        self.Label5_2_1.configure(anchor='w')
        self.Label5_2_1.configure(compound='left')
        self.Label5_2_1.configure(font="-family {DejaVu Sans} -size 10")
        self.Label5_2_1.configure(text='''Recording:''')

        self.Label7_2_1 = tk.Label(self.stitch_360low_block)
        self.Label7_2_1.place(relx=0.624, rely=0.677, height=20, width=66
                , bordermode='ignore')
        self.Label7_2_1.configure(activebackground="#f9f9f9")
        self.Label7_2_1.configure(anchor='w')
        self.Label7_2_1.configure(compound='left')
        self.Label7_2_1.configure(font="-family {DejaVu Sans} -size 10")
        self.Label7_2_1.configure(text='''Status:''')

        self.stitch_360low_status = tk.Label(self.stitch_360low_block)
        self.stitch_360low_status.place(relx=0.72, rely=0.677, height=20
                , width=140, bordermode='ignore')
        self.stitch_360low_status.configure(activebackground="#f9f9f9")
        self.stitch_360low_status.configure(anchor='w')
        self.stitch_360low_status.configure(compound='left')
        self.stitch_360low_status.configure(font="-family {DejaVu Sans} -size 10")
        self.stitch_360low_status.configure(text='''None''')

        self.stitch_360low_threads = tk.Spinbox(self.stitch_360low_block, from_=1.0, to=100.0)
        self.stitch_360low_threads.place(relx=0.223, rely=0.253, relheight=0.212
                , relwidth=0.119, bordermode='ignore')
        self.stitch_360low_threads.configure(activebackground="#f9f9f9")
        self.stitch_360low_threads.configure(background="white")
        self.stitch_360low_threads.configure(font="-family {DejaVu Sans} -size 10")
        self.stitch_360low_threads.configure(highlightbackground="black")
        self.stitch_360low_threads.configure(selectbackground="#c4c4c4")
        self.value_list = ['5',]
        self.stitch_360low_threads.configure(values=self.value_list)
        self.stitch_360low_threads.configure(wrap="1")

        self.stitch_360_label = tk.Label(self.stitch_360low_block)
        self.stitch_360_label.place(relx=0.029, rely=0.253, height=25, width=123
                , bordermode='ignore')
        self.stitch_360_label.configure(activebackground="#f9f9f9")
        self.stitch_360_label.configure(anchor='w')
        self.stitch_360_label.configure(compound='left')
        self.stitch_360_label.configure(font="-family {DejaVu Sans} -size 10")
        self.stitch_360_label.configure(text='''No of Threads''')

        self.upload_360low = tk.Button(self.stitch_360low_block)
        self.upload_360low.place(relx=0.292, rely=0.596, height=33, width=73
                , bordermode='ignore')
        self.upload_360low.configure(activebackground="beige")
        self.upload_360low.configure(borderwidth="2")
        self.upload_360low.configure(command=project1_support.upload_360low)
        self.upload_360low.configure(compound='left')
        self.upload_360low.configure(font="-family {DejaVu Sans} -size 10")
        self.upload_360low.configure(text='''Upload''')

        self.stitch_360low_rec = tk.Label(self.stitch_360low_block)
        self.stitch_360low_rec.place(relx=0.784, rely=0.455, height=20, width=65
                , bordermode='ignore')
        self.stitch_360low_rec.configure(activebackground="#f9f9f9")
        self.stitch_360low_rec.configure(anchor='w')
        self.stitch_360low_rec.configure(compound='left')
        self.stitch_360low_rec.configure(font="-family {DejaVu Sans} -size 10")
        self.stitch_360low_rec.configure(text='''0''')

        self.quality_block = tk.LabelFrame(self.top)
        self.quality_block.place(relx=0.029, rely=0.867, relheight=0.074
                , relwidth=0.946)
        self.quality_block.configure(relief='groove')
        self.quality_block.configure(font="-family {DejaVu Sans} -size 10")
        self.quality_block.configure(text='''Generate Quality File''')

        self.generate_quality = ttk.Button(self.quality_block)
        self.generate_quality.place(relx=0.031, rely=0.348, height=31, width=80
                , bordermode='ignore')
        self.generate_quality.configure(command=project1_support.generate_quality_file)
        self.generate_quality.configure(text='''Start''')
        self.generate_quality.configure(compound='left')

        self.upload_quality = tk.Button(self.quality_block)
        self.upload_quality.place(relx=0.263, rely=0.303, height=33, width=73
                , bordermode='ignore')
        self.upload_quality.configure(activebackground="beige")
        self.upload_quality.configure(borderwidth="2")
        self.upload_quality.configure(command=project1_support.upload_quality_file)
        self.upload_quality.configure(compound='left')
        self.upload_quality.configure(font="-family {DejaVu Sans} -size 10")
        self.upload_quality.configure(text='''Upload''')

        self.process_jpg_block = tk.LabelFrame(self.top)
        self.process_jpg_block.place(relx=0.029, rely=0.338, relheight=0.115
                , relwidth=0.944)
        self.process_jpg_block.configure(relief='groove')
        self.process_jpg_block.configure(font="-family {DejaVu Sans} -size 10")
        self.process_jpg_block.configure(text='''Process JPG''')

        self.Label5_2 = tk.Label(self.process_jpg_block)
        self.Label5_2.place(relx=0.633, rely=0.451, height=21, width=103
                , bordermode='ignore')
        self.Label5_2.configure(activebackground="#f9f9f9")
        self.Label5_2.configure(anchor='w')
        self.Label5_2.configure(compound='left')
        self.Label5_2.configure(font="-family {DejaVu Sans} -size 10")
        self.Label5_2.configure(text='''Recording:''')

        self.process_jpg_rec = tk.Label(self.process_jpg_block)
        self.process_jpg_rec.place(relx=0.783, rely=0.451, height=21, width=65
                , bordermode='ignore')
        self.process_jpg_rec.configure(activebackground="#f9f9f9")
        self.process_jpg_rec.configure(anchor='w')
        self.process_jpg_rec.configure(compound='left')
        self.process_jpg_rec.configure(font="-family {DejaVu Sans} -size 10")
        self.process_jpg_rec.configure(text='''0''')

        self.Label7_2 = tk.Label(self.process_jpg_block)
        self.Label7_2.place(relx=0.624, rely=0.676, height=21, width=66
                , bordermode='ignore')
        self.Label7_2.configure(activebackground="#f9f9f9")
        self.Label7_2.configure(anchor='w')
        self.Label7_2.configure(compound='left')
        self.Label7_2.configure(font="-family {DejaVu Sans} -size 10")
        self.Label7_2.configure(text='''Status:''')

        self.process_jpg_status = tk.Label(self.process_jpg_block)
        self.process_jpg_status.place(relx=0.72, rely=0.676, height=21, width=140
                , bordermode='ignore')
        self.process_jpg_status.configure(activebackground="#f9f9f9")
        self.process_jpg_status.configure(anchor='w')
        self.process_jpg_status.configure(compound='left')
        self.process_jpg_status.configure(font="-family {DejaVu Sans} -size 10")
        self.process_jpg_status.configure(text='''None''')

        self.jpg_threads = tk.Spinbox(self.process_jpg_block, from_=1.0, to=100.0)
        self.jpg_threads.place(relx=0.218, rely=0.255, relheight=0.216
                , relwidth=0.119, bordermode='ignore')
        self.jpg_threads.configure(activebackground="#f9f9f9")
        self.jpg_threads.configure(background="white")
        self.jpg_threads.configure(font="-family {DejaVu Sans} -size 10")
        self.jpg_threads.configure(highlightbackground="black")
        self.jpg_threads.configure(selectbackground="#c4c4c4")
        self.value_list = ['200',]
        self.jpg_threads.configure(values=self.value_list)

        self.jpg_label = tk.Label(self.process_jpg_block)
        self.jpg_label.place(relx=0.029, rely=0.255, height=25, width=122
                , bordermode='ignore')
        self.jpg_label.configure(activebackground="#f9f9f9")
        self.jpg_label.configure(anchor='w')
        self.jpg_label.configure(compound='left')
        self.jpg_label.configure(font="-family {DejaVu Sans} -size 10")
        self.jpg_label.configure(text='''No of Threads''')

        self.process_jpg = ttk.Progressbar(self.process_jpg_block)
        self.process_jpg.place(relx=0.554, rely=0.255, relwidth=0.41
                , relheight=0.0, height=19, bordermode='ignore')
        self.process_jpg.configure(length="281")

        self.upload_jpg = tk.Button(self.process_jpg_block)
        self.upload_jpg.place(relx=0.231, rely=0.598, height=33, width=73
                , bordermode='ignore')
        self.upload_jpg.configure(activebackground="beige")
        self.upload_jpg.configure(borderwidth="2")
        self.upload_jpg.configure(command=project1_support.upload_jpg)
        self.upload_jpg.configure(compound='left')
        self.upload_jpg.configure(font="-family {DejaVu Sans} -size 10")
        self.upload_jpg.configure(text='''Upload''')

        self.start_process_jpg = ttk.Button(self.process_jpg_block)
        self.start_process_jpg.place(relx=0.073, rely=0.588, height=31, width=80
                , bordermode='ignore')
        self.start_process_jpg.configure(command=project1_support.start_process_jpg)
        self.start_process_jpg.configure(text='''Start''')
        self.start_process_jpg.configure(compound='left')

        self.start_jpg_crop = ttk.Button(self.process_jpg_block)
        self.start_jpg_crop.place(relx=0.387, rely=0.196, height=31, width=80
                , bordermode='ignore')
        self.start_jpg_crop.configure(command=project1_support.start_jpg_crop)
        self.start_jpg_crop.configure(text='''Crop''')
        self.start_jpg_crop.configure(compound='left')

        self.upload_jpg_crop = ttk.Button(self.process_jpg_block)
        self.upload_jpg_crop.place(relx=0.387, rely=0.588, height=31, width=100
                , bordermode='ignore')
        self.upload_jpg_crop.configure(command=project1_support.upload_jpg_crop)
        self.upload_jpg_crop.configure(text='''Upload Crop''')
        self.upload_jpg_crop.configure(compound='left')

        self.blurring_block = tk.LabelFrame(self.top)
        self.blurring_block.place(relx=0.029, rely=0.462, relheight=0.128
                , relwidth=0.944)
        self.blurring_block.configure(relief='groove')
        self.blurring_block.configure(font="-family {DejaVu Sans} -size 10")
        self.blurring_block.configure(text='''Blurring''')

        self.Label5_2_2 = tk.Label(self.blurring_block)
        self.Label5_2_2.place(relx=0.633, rely=0.456, height=23, width=103
                , bordermode='ignore')
        self.Label5_2_2.configure(activebackground="#f9f9f9")
        self.Label5_2_2.configure(anchor='w')
        self.Label5_2_2.configure(compound='left')
        self.Label5_2_2.configure(font="-family {DejaVu Sans} -size 10")
        self.Label5_2_2.configure(text='''Recording:''')

        self.Label7_2_2 = tk.Label(self.blurring_block)
        self.Label7_2_2.place(relx=0.624, rely=0.684, height=23, width=66
                , bordermode='ignore')
        self.Label7_2_2.configure(activebackground="#f9f9f9")
        self.Label7_2_2.configure(anchor='w')
        self.Label7_2_2.configure(compound='left')
        self.Label7_2_2.configure(font="-family {DejaVu Sans} -size 10")
        self.Label7_2_2.configure(text='''Status:''')

        self.blurring_rec = tk.Label(self.blurring_block)
        self.blurring_rec.place(relx=0.783, rely=0.456, height=23, width=65
                , bordermode='ignore')
        self.blurring_rec.configure(activebackground="#f9f9f9")
        self.blurring_rec.configure(anchor='w')
        self.blurring_rec.configure(compound='left')
        self.blurring_rec.configure(font="-family {DejaVu Sans} -size 10")
        self.blurring_rec.configure(text='''0''')

        self.blurring_status = tk.Label(self.blurring_block)
        self.blurring_status.place(relx=0.72, rely=0.684, height=23, width=140
                , bordermode='ignore')
        self.blurring_status.configure(activebackground="#f9f9f9")
        self.blurring_status.configure(anchor='w')
        self.blurring_status.configure(compound='left')
        self.blurring_status.configure(font="-family {DejaVu Sans} -size 10")
        self.blurring_status.configure(text='''None''')

        self.upload_jpgblur = tk.Button(self.blurring_block)
        self.upload_jpgblur.place(relx=0.406, rely=0.588, height=33, width=73
                , bordermode='ignore')
        self.upload_jpgblur.configure(activebackground="beige")
        self.upload_jpgblur.configure(borderwidth="2")
        self.upload_jpgblur.configure(command=project1_support.upload_jpgblur)
        self.upload_jpgblur.configure(compound='left')
        self.upload_jpgblur.configure(font="-family {DejaVu Sans} -size 10")
        self.upload_jpgblur.configure(text='''Upload''')

        self.download_recon = ttk.Button(self.blurring_block)
        self.download_recon.place(relx=0.028, rely=0.588, height=31, width=130
                , bordermode='ignore')
        self.download_recon.configure(command=project1_support.download_recon)
        self.download_recon.configure(text='''Download Recon''')
        self.download_recon.configure(compound='left')

        self.blur_threads = tk.Spinbox(self.blurring_block, from_=1.0, to=100.0)
        self.blur_threads.place(relx=0.218, rely=0.254, relheight=0.219
                , relwidth=0.119, bordermode='ignore')
        self.blur_threads.configure(activebackground="#f9f9f9")
        self.blur_threads.configure(background="white")
        self.blur_threads.configure(font="-family {DejaVu Sans} -size 10")
        self.blur_threads.configure(highlightbackground="black")
        self.blur_threads.configure(selectbackground="#c4c4c4")
        self.value_list = ['10',]
        self.blur_threads.configure(values=self.value_list)

        self.blurring_label = tk.Label(self.blurring_block)
        self.blurring_label.place(relx=0.029, rely=0.254, height=28, width=122
                , bordermode='ignore')
        self.blurring_label.configure(activebackground="#f9f9f9")
        self.blurring_label.configure(anchor='w')
        self.blurring_label.configure(compound='left')
        self.blurring_label.configure(font="-family {DejaVu Sans} -size 10")
        self.blurring_label.configure(text='''No of Threads''')

        self.blurring = ttk.Progressbar(self.blurring_block)
        self.blurring.place(relx=0.554, rely=0.263, relwidth=0.41, relheight=0.0
                , height=19, bordermode='ignore')
        self.blurring.configure(length="281")

        self.start_blurring = ttk.Button(self.blurring_block)
        self.start_blurring.place(relx=0.252, rely=0.588, height=31, width=80
                , bordermode='ignore')
        self.start_blurring.configure(command=project1_support.start_blurring)
        self.start_blurring.configure(text='''Start''')
        self.start_blurring.configure(compound='left')

        self.configs_block = ttk.Labelframe(self.top)
        self.configs_block.place(relx=0.028, rely=0.012, relheight=0.119
                , relwidth=0.942)
        self.configs_block.configure(relief='')
        self.configs_block.configure(text='''Configs''')

        self.Label1_1 = tk.Label(self.configs_block)
        self.Label1_1.place(relx=0.286, rely=1.481, height=18, width=73
                , bordermode='ignore')
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(anchor='w')
        self.Label1_1.configure(compound='left')
        self.Label1_1.configure(font="-family {DejaVu Sans} -size 10")
        self.Label1_1.configure(text='''Input Dir''')

        self.select_project = tk.Button(self.configs_block)
        self.select_project.place(relx=0.278, rely=0.226, height=33, width=133
                , bordermode='ignore')
        self.select_project.configure(activebackground="beige")
        self.select_project.configure(borderwidth="2")
        self.select_project.configure(command=project1_support.select_project)
        self.select_project.configure(compound='left')
        self.select_project.configure(font="-family {DejaVu Sans} -size 10")
        self.select_project.configure(text='''Select Project''')

        self.select_recording = tk.Button(self.configs_block)
        self.select_recording.place(relx=0.281, rely=0.604, height=33, width=133
                , bordermode='ignore')
        self.select_recording.configure(activebackground="beige")
        self.select_recording.configure(borderwidth="2")
        self.select_recording.configure(command=project1_support.select_recording)
        self.select_recording.configure(compound='left')
        self.select_recording.configure(font="-family {DejaVu Sans} -size 10")
        self.select_recording.configure(text='''Select Recording''')

        self.Label4_1_1 = tk.Label(self.configs_block)
        self.Label4_1_1.place(relx=0.54, rely=0.292, height=14, width=65
                , bordermode='ignore')
        self.Label4_1_1.configure(activebackground="#f9f9f9")
        self.Label4_1_1.configure(anchor='w')
        self.Label4_1_1.configure(compound='left')
        self.Label4_1_1.configure(font="-family {DejaVu Sans} -size 10")
        self.Label4_1_1.configure(text='''Project:''')

        self.Label4_2 = tk.Label(self.configs_block)
        self.Label4_2.place(relx=0.54, rely=0.594, height=20, width=76
                , bordermode='ignore')
        self.Label4_2.configure(activebackground="#f9f9f9")
        self.Label4_2.configure(anchor='w')
        self.Label4_2.configure(compound='left')
        self.Label4_2.configure(font="-family {DejaVu Sans} -size 10")
        self.Label4_2.configure(text='''Recording:''')

        self.rec_num = tk.Label(self.configs_block)
        self.rec_num.place(relx=0.671, rely=0.632, height=12, width=94
                , bordermode='ignore')
        self.rec_num.configure(activebackground="#f9f9f9")
        self.rec_num.configure(anchor='w')
        self.rec_num.configure(compound='left')
        self.rec_num.configure(font="-family {DejaVu Sans} -size 10")
        self.rec_num.configure(text='''0''')

        self.Label1 = tk.Label(self.configs_block)
        self.Label1.place(relx=0.076, rely=0.264, height=17, width=73
                , bordermode='ignore')
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(anchor='w')
        self.Label1.configure(compound='left')
        self.Label1.configure(font="-family {DejaVu Sans} -size 10")
        self.Label1.configure(text='''Select Disk''')

        self.project_name = tk.Label(self.configs_block)
        self.project_name.place(relx=0.643, rely=0.292, height=14, width=216
                , bordermode='ignore')
        self.project_name.configure(activebackground="#f9f9f9")
        self.project_name.configure(anchor='w')
        self.project_name.configure(compound='left')
        self.project_name.configure(font="-family {DejaVu Sans} -size 10")
        self.project_name.configure(text='''Unknown''')

        self.select_s16 = tk.Radiobutton(self.configs_block)
        self.select_s16.place(relx=0.043, rely=0.443, relheight=0.17
                , relwidth=0.098, bordermode='ignore')
        self.select_s16.configure(activebackground="beige")
        self.select_s16.configure(anchor='w')
        self.select_s16.configure(command=project1_support.select_s16)
        self.select_s16.configure(compound='left')
        self.select_s16.configure(font="-family {DejaVu Sans} -size 10")
        self.select_s16.configure(justify='left')
        self.select_s16.configure(selectcolor="#d9d9d9")
        self.select_s16.configure(text='''s16''')
        self.select_s16.configure(value='0')
        self.select_s16.configure(variable=self.selectedButton)

        self.select_s16_1_1 = tk.Radiobutton(self.configs_block)
        self.select_s16_1_1.place(relx=0.132, rely=0.443, relheight=0.17
                , relwidth=0.098, bordermode='ignore')
        self.select_s16_1_1.configure(activebackground="beige")
        self.select_s16_1_1.configure(anchor='w')
        self.select_s16_1_1.configure(command=project1_support.select_s17e)
        self.select_s16_1_1.configure(compound='left')
        self.select_s16_1_1.configure(font="-family {DejaVu Sans} -size 10")
        self.select_s16_1_1.configure(justify='left')
        self.select_s16_1_1.configure(selectcolor="#d9d9d9")
        self.select_s16_1_1.configure(text='''s17e''')
        self.select_s16_1_1.configure(value='3')
        self.select_s16_1_1.configure(variable=self.selectedButton)

        self.select_s16_1_1_1 = tk.Radiobutton(self.configs_block)
        self.select_s16_1_1_1.place(relx=0.132, rely=0.613, relheight=0.17
                , relwidth=0.098, bordermode='ignore')
        self.select_s16_1_1_1.configure(activebackground="beige")
        self.select_s16_1_1_1.configure(anchor='w')
        self.select_s16_1_1_1.configure(command=project1_support.select_s18g)
        self.select_s16_1_1_1.configure(compound='left')
        self.select_s16_1_1_1.configure(font="-family {DejaVu Sans} -size 10")
        self.select_s16_1_1_1.configure(justify='left')
        self.select_s16_1_1_1.configure(selectcolor="#d9d9d9")
        self.select_s16_1_1_1.configure(text='''s18g''')
        self.select_s16_1_1_1.configure(value='4')
        self.select_s16_1_1_1.configure(variable=self.selectedButton)

        self.select_s17 = tk.Radiobutton(self.configs_block)
        self.select_s17.place(relx=0.043, rely=0.613, relheight=0.17
                , relwidth=0.098, bordermode='ignore')
        self.select_s17.configure(activebackground="beige")
        self.select_s17.configure(anchor='w')
        self.select_s17.configure(command=project1_support.select_s17)
        self.select_s17.configure(compound='left')
        self.select_s17.configure(font="-family {DejaVu Sans} -size 10")
        self.select_s17.configure(justify='left')
        self.select_s17.configure(selectcolor="#d9d9d9")
        self.select_s17.configure(text='''s17''')
        self.select_s17.configure(value='1')
        self.select_s17.configure(variable=self.selectedButton)

        self.select_s18 = tk.Radiobutton(self.configs_block)
        self.select_s18.place(relx=0.043, rely=0.802, relheight=0.17
                , relwidth=0.098, bordermode='ignore')
        self.select_s18.configure(activebackground="beige")
        self.select_s18.configure(anchor='w')
        self.select_s18.configure(command=project1_support.select_s18)
        self.select_s18.configure(compound='left')
        self.select_s18.configure(font="-family {DejaVu Sans} -size 10")
        self.select_s18.configure(justify='left')
        self.select_s18.configure(selectcolor="#d9d9d9")
        self.select_s18.configure(text='''s18''')
        self.select_s18.configure(value='2')
        self.select_s18.configure(variable=self.selectedButton)

        self.select_s21 = tk.Radiobutton(self.configs_block)
        self.select_s21.place(relx=0.132, rely=0.783, relheight=0.17
                , relwidth=0.098, bordermode='ignore')
        self.select_s21.configure(activebackground="beige")
        self.select_s21.configure(anchor='w')
        self.select_s21.configure(command=project1_support.select_s21)
        self.select_s21.configure(compound='left')
        self.select_s21.configure(font="-family {DejaVu Sans} -size 10")
        self.select_s21.configure(justify='left')
        self.select_s21.configure(selectcolor="#d9d9d9")
        self.select_s21.configure(text='''s21d''')
        self.select_s21.configure(value='5')
        self.select_s21.configure(variable=self.selectedButton)

        self.preprocess_block = tk.LabelFrame(self.top)
        self.preprocess_block.place(relx=0.028, rely=0.137, relheight=0.071
                , relwidth=0.946)
        self.preprocess_block.configure(relief='groove')
        self.preprocess_block.configure(font="-family {DejaVu Sans} -size 10")
        self.preprocess_block.configure(text='''Pre Process''')

        self.start_preprocess = ttk.Button(self.preprocess_block)
        self.start_preprocess.place(relx=0.073, rely=0.349, height=31, width=80
                , bordermode='ignore')
        self.start_preprocess.configure(command=project1_support.start_preprocess)
        self.start_preprocess.configure(text='''Start''')
        self.start_preprocess.configure(compound='left')

class select_rec:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("788x987+1096+27")
        top.minsize(1, 1)
        top.maxsize(1905, 1050)
        top.resizable(1,  1)
        top.title("Select Recordings")

        self.top = top

        self.close_select_rec = tk.Button(self.top)
        self.close_select_rec.place(relx=0.444, rely=0.956, height=36, width=89)
        self.close_select_rec.configure(activebackground="beige")
        self.close_select_rec.configure(borderwidth="2")
        self.close_select_rec.configure(command=project1_support.close_select_rec)
        self.close_select_rec.configure(compound='left')
        self.close_select_rec.configure(font="-family {DejaVu Sans} -size 10")
        self.close_select_rec.configure(text='''Select''')

        self.recordings = tk.LabelFrame(self.top)
        self.recordings.place(relx=0.016, rely=0.002, relheight=0.95
                , relwidth=0.972)
        self.recordings.configure(relief='groove')
        self.recordings.configure(font="-family {DejaVu Sans} -size 10")
        self.recordings.configure(text='''Recordings''')

class project:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("1019x938+196+913")
        top.minsize(1, 1)
        top.maxsize(1905, 1050)
        top.resizable(1,  1)
        top.title("Select Project")

        self.top = top

        self.close_select_prj = tk.Button(self.top)
        self.close_select_prj.place(relx=0.461, rely=0.957, height=33, width=73)
        self.close_select_prj.configure(activebackground="beige")
        self.close_select_prj.configure(borderwidth="2")
        self.close_select_prj.configure(command=project1_support.close_select_prj)
        self.close_select_prj.configure(compound='left')
        self.close_select_prj.configure(font="-family {DejaVu Sans} -size 10")
        self.close_select_prj.configure(text='''Select''')

        self.projects = tk.LabelFrame(self.top)
        self.projects.place(relx=0.02, rely=0.011, relheight=0.934
                , relwidth=0.966)
        self.projects.configure(relief='groove')
        self.projects.configure(font="-family {DejaVu Sans} -size 10")
        self.projects.configure(text='''Projects''')

def start_up():
    project1_support.main()

if __name__ == '__main__':
    project1_support.main()




